name: Two Jobs Test
on: [push]
jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - run: mkdir -p path/to/artifact
      - run: echo "A" > path/to/artifact/note.txt
      - run: cat path/to/artifact/note.txt
      - uses: actions/upload-artifact@v7
        with:
          path: path/to/artifact/note.txt
          archive: false
  two:
    needs: one
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v7
        with:
          path: path/to/artifact/note.txt
      - run: cat path/to/artifact/note.txt
